title: Bram van Dam
kicker: Editor - Colorist - Filmmaker
author:
  name: Bram van Dam
  email: 'b.vandam@rodekaterproducties.nl'
metadata:
    description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
taxonomies: [category,tag,brand]
